# docker stack deploy -c docker-stack.yml <name>

version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      PWD: /run/secrets/mongoPWD
    secrets:
      - mongoPWD
      - mongoUSR
    networks:
      - traefik-net
    ports: 
      - 27017:27017
    volumes: 
      - mongo-data:/data/db
    deploy:
      labels:
        traefik.port: 27017
      restart_policy:
        condition: on-failure

  api:
    image: arjunr11/blabber
    read_only: true
    volumes:
      - ./:/src
    networks:
      - traefik-net
    secrets:
      - mongoPWD
    deploy:
      replicas: 2
      labels:
        traefik.backend: api
        traefik.docker.network: traefik-net
        traefik.frontend.rule: PathPrefixStrip:/api
      restart_policy:
        condition: on-failure

  reverse-proxy:
    image: traefik
    command: --api --docker --docker.swarmMode
    networks:
      - traefik-net
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        traefik.docker.network: traefik-net
      placement:
        constraints: 
          - node.role == manager

  client:
    image: vtcs2304s19/blabber-client
    networks:
      - traefik-net
    deploy:
      replicas: 2
      labels:
        traefik.backend: client
        traefik.frontend.rule: PathPrefix:/
        traefik.port: 80
        traefik.docker.network: traefik-net

  swarm-viz:
    image: mikesir87/swarm-viz
    ports: 
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: 
          - node.role == manager

volumes:
  mongo-data:
networks:
  traefik-net:
secrets:
  mongoPWD:
    file: ./DB_PASSWORD_FILE
  