# docker stack deploy -c docker-stack.yml <name>

version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - traefik-net
    ports: 
      - 27017:27017
    volumes: 
      - mongo-data:/data/db
    deploy:
      labels:
        - traefik.port: 27017
      restart_policy:
        condition: on-failure

  api:
    image: blabber
    volumes:
      - ./:/src
    networks:
      - traefik-net
    deploy:
      replicas: 2
      labels:
        traefik.backend: api
        traefik.frontend.rule: PathPrefixStrip:/api

  reverse-proxy:
    image: traefik
    command: --api --docker
    networks:
      - traefik-net
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  client:
    image: vtcs2304s19/blabber-client
    networks:
      - traefik-net
    deploy:
      replicas: 2
      labels:
        traefik.backend: client
        traefik.frontend.rule: PathPrefix:/
        traefik.port: 80

volumes:
  mongo-data:
networks:
  traefik-net: