#docker-compose up

version: '3.7'

services:
  mongo:
    image: mongo
    networks:
      - traefik-net
    command: mongod --dbpath ./data/db
    restart: always
    ports: 
      - 27017:27017
    volumes: 
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  api:
    image: arjunr11/blabber
    read_only: true
    environment:
      mongoUSR: /run/secrets/DB_PASSWORD_FILE
      mongoPWD: /run/secrets/DB_PASSWORD_FILE
    networks:
      - traefik-net
    volumes:
      - ./:/src
    depends_on:
      - mongo
    labels:
      traefik.backend: api
      traefik.frontend.rule: PathPrefixStrip:/api
    

  reverse-proxy:
    image: traefik
    networks:
      - traefik-net
    command: --api --docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  client:
    image: vtcs2304s19/blabber-client
    networks:
      - traefik-net
    labels:
      traefik.backend: client
      traefik.frontend.rule: PathPrefix:/
      traefik.port: 80

volumes:
  mongo-data:
  mongo-config:
networks:
  traefik-net:
    