version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    volumes: 
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    deploy:


  api:
    image: blabber
    volumes:
      - ./:/src
    labels:
      traefik.backend: api
      traefik.frontend.rule: PathPrefixStrip:/api

  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  client:
    image: vtcs2304s19/blabber-client
    labels:
      traefik.backend: client
      traefik.frontend.rule: PathPrefix:/
      traefik.port: 80

  tests:
    image: vtcs2304s19/blabber-api-tests
    environment:
      SERVICE_NAME: api
      API_PORT: "3000"
    depends_on:
      - api

volumes:
  mongo-data:
  mongo-config:
    